server:
  port: 8080
spring:
  datasourse:
    username: root
    password: 171024
    url: jdbc:mysql://127.0.0.1:3306/bsp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-location: classpath:mappers/*/*Mapper.xml
    type-aliases-package: com.neusoft.bsp.*.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl